const DEFAULT_MOMENT_FORMAT = 'YYYY-MM-DD hh:mm A';
const DEFAULT_MOMENT_FORMAT_DATE_ONLY = 'YYYY-MM-DD';
const DEFAULT_MOMENT_FORMAT_DATE_ONLY_FOR_DE = 'DD.MM.YYYY';
const DEFAULT_PICKER_FORMAT = 'yyyy-MM-dd hh:mm a';
const DEFAULT_PICKER_FORMAT_DATE_ONLY = 'yyyy-MM-dd';

export {
  DEFAULT_MOMENT_FORMAT,
  DEFAULT_MOMENT_FORMAT_DATE_ONLY,
  DEFAULT_MOMENT_FORMAT_DATE_ONLY_FOR_DE,
  DEFAULT_PICKER_FORMAT,
  DEFAULT_PICKER_FORMAT_DATE_ONLY,
};
