const DEFAULT_MOMENT_FORMAT = 'HH:mm:ss DD.MM.YYYY';
const DEFAULT_MOMENT_FORMAT_DATE_ONLY = 'DD.MM.YYYY';
const DEFAULT_PICKER_FORMAT = 'yyyy-MM-dd hh:mm a';
const DEFAULT_PICKER_FORMAT_DATE_ONLY = 'yyyy-MM-dd';

export {
  DEFAULT_MOMENT_FORMAT,
  DEFAULT_MOMENT_FORMAT_DATE_ONLY,
  DEFAULT_PICKER_FORMAT,
  DEFAULT_PICKER_FORMAT_DATE_ONLY,
};
